### ISSUE TITLE
报错了~

### ISSUE THREAD

**Issue by Neo01010** [Nitr4x/whichCDN#8]
![default](https://cloud.githubusercontent.com/assets/15312660/23593888/ccaa5774-024f-11e7-9f4f-c7e6b53a3090.png)

**Comment by Nitr4x** [comment]
WhichCDN is fully functional on MacOS and UNIX. I will check this out ASAP. Thanks for your input.

**Comment by Nitr4x** [comment]
Hi, a quick search on google should give you the answer.

https://stackoverflow.com/questions/16371421/python-signal-dont-work-even-on-cygwin

Indeed,to make work signal module on windows OS, python has to be installed through cygwin. I followed the installation procedure and everything worked fine.

![proof](https://cloud.githubusercontent.com/assets/10544300/23792392/00e833be-0587-11e7-9c0d-9fdf3100021d.png)

I close the issue.
